
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action FileAction;
	private global::Gtk.Action FileAction1;
	private global::Gtk.Action QuitAction;
	private global::Gtk.Action AccountAction;
	private global::Gtk.Action LogOutAction;
	private global::Gtk.VBox MainContainer;
	private global::Gtk.MenuBar FileMenuBar;
	private global::Gtk.VBox PrimaryContainer;
	private global::Gtk.HBox TopBarContainer;
	private global::Gtk.VBox MySubredditContainer;
	private global::Gtk.Label MySubredditsLabel;
	private global::Gtk.ComboBox mySubredditsBox;
	private global::Gtk.Button AddSubBtn;
	private global::Gtk.VSeparator vseparator1;
	private global::Gtk.VBox BrowseRedditContainer;
	private global::Gtk.HBox BrowseRedditLabelContainer;
	private global::Gtk.Label BrowseRedditLabel;
	private global::Gtk.Alignment BrowseRedditAligner;
	private global::Gtk.ScrolledWindow BrowseBtnsScrollWindow;
	private global::Gtk.HBox BrowseBtnBox;
	private global::Gtk.VSeparator vseparator2;
	private global::Gtk.VBox SearchContainer;
	private global::Gtk.Label SearchLabel;
	private global::Gtk.HBox SearchOptsContainer;
	private global::Gtk.CheckButton searchThisSub;
	private global::Gtk.CheckButton searchNsfw;
	private global::Gtk.HBox SearchBarContainer;
	private global::Gtk.Entry SearchEntry;
	private global::Gtk.Button SearchBtn;
	private global::Gtk.VBox ContentContainer;
	private global::Gtk.HPaned ContentPane;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.VBox ListingBox;
	private global::Gtk.Fixed fixed1;
	private global::Gtk.HBox BottomBarContainer;
	private global::Gtk.VBox NotifyContainer;
	private global::Gtk.HBox NotifyLabelBox;
	private global::Gtk.Label NotifyLabel;
	private global::Gtk.HBox NotifyBtnContainer;
	private global::Gtk.Button messagesBtn;
	private global::Gtk.Button comRepliesBtn;
	private global::Gtk.Button PostRepliesBtn;
	private global::Gtk.VSeparator vseparator3;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.FileAction1 = new global::Gtk.Action ("FileAction1", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction1, null);
		this.QuitAction = new global::Gtk.Action ("QuitAction", global::Mono.Unix.Catalog.GetString ("Quit"), null, null);
		this.QuitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Quit");
		w1.Add (this.QuitAction, null);
		this.AccountAction = new global::Gtk.Action ("AccountAction", global::Mono.Unix.Catalog.GetString ("Account"), null, null);
		this.AccountAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Account");
		w1.Add (this.AccountAction, null);
		this.LogOutAction = new global::Gtk.Action ("LogOutAction", global::Mono.Unix.Catalog.GetString ("Log out"), null, null);
		this.LogOutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Log out");
		w1.Add (this.LogOutAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.WidthRequest = 900;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Reddit Desktop");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		this.DefaultWidth = 700;
		this.DefaultHeight = 500;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.MainContainer = new global::Gtk.VBox ();
		this.MainContainer.Name = "MainContainer";
		this.MainContainer.Spacing = 6;
		// Container child MainContainer.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='FileMenuBar'><menu name='FileAction1' action='FileAction1'><menuitem name='QuitAction' action='QuitAction'/></menu><menu name='AccountAction' action='AccountAction'><menuitem name='LogOutAction' action='LogOutAction'/></menu></menubar></ui>");
		this.FileMenuBar = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/FileMenuBar")));
		this.FileMenuBar.Name = "FileMenuBar";
		this.MainContainer.Add (this.FileMenuBar);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.MainContainer [this.FileMenuBar]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child MainContainer.Gtk.Box+BoxChild
		this.PrimaryContainer = new global::Gtk.VBox ();
		this.PrimaryContainer.Name = "PrimaryContainer";
		this.PrimaryContainer.Spacing = 6;
		// Container child PrimaryContainer.Gtk.Box+BoxChild
		this.TopBarContainer = new global::Gtk.HBox ();
		this.TopBarContainer.Name = "TopBarContainer";
		this.TopBarContainer.Spacing = 6;
		this.TopBarContainer.BorderWidth = ((uint)(13));
		// Container child TopBarContainer.Gtk.Box+BoxChild
		this.MySubredditContainer = new global::Gtk.VBox ();
		this.MySubredditContainer.Name = "MySubredditContainer";
		this.MySubredditContainer.Spacing = 6;
		// Container child MySubredditContainer.Gtk.Box+BoxChild
		this.MySubredditsLabel = new global::Gtk.Label ();
		this.MySubredditsLabel.Name = "MySubredditsLabel";
		this.MySubredditsLabel.Xalign = 0F;
		this.MySubredditsLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("MY SUBREDDITS");
		this.MySubredditContainer.Add (this.MySubredditsLabel);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.MySubredditContainer [this.MySubredditsLabel]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child MySubredditContainer.Gtk.Box+BoxChild
		this.mySubredditsBox = global::Gtk.ComboBox.NewText ();
		this.mySubredditsBox.WidthRequest = 200;
		this.mySubredditsBox.Name = "mySubredditsBox";
		this.MySubredditContainer.Add (this.mySubredditsBox);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.MySubredditContainer [this.mySubredditsBox]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		// Container child MySubredditContainer.Gtk.Box+BoxChild
		this.AddSubBtn = new global::Gtk.Button ();
		this.AddSubBtn.CanFocus = true;
		this.AddSubBtn.Name = "AddSubBtn";
		this.AddSubBtn.UseUnderline = true;
		this.AddSubBtn.Label = global::Mono.Unix.Catalog.GetString ("Subscribe..");
		this.MySubredditContainer.Add (this.AddSubBtn);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.MySubredditContainer [this.AddSubBtn]));
		w5.PackType = ((global::Gtk.PackType)(1));
		w5.Position = 2;
		w5.Expand = false;
		w5.Fill = false;
		this.TopBarContainer.Add (this.MySubredditContainer);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.TopBarContainer [this.MySubredditContainer]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child TopBarContainer.Gtk.Box+BoxChild
		this.vseparator1 = new global::Gtk.VSeparator ();
		this.vseparator1.Name = "vseparator1";
		this.TopBarContainer.Add (this.vseparator1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.TopBarContainer [this.vseparator1]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		// Container child TopBarContainer.Gtk.Box+BoxChild
		this.BrowseRedditContainer = new global::Gtk.VBox ();
		this.BrowseRedditContainer.Name = "BrowseRedditContainer";
		this.BrowseRedditContainer.Spacing = 6;
		// Container child BrowseRedditContainer.Gtk.Box+BoxChild
		this.BrowseRedditLabelContainer = new global::Gtk.HBox ();
		this.BrowseRedditLabelContainer.Name = "BrowseRedditLabelContainer";
		this.BrowseRedditLabelContainer.Spacing = 6;
		// Container child BrowseRedditLabelContainer.Gtk.Box+BoxChild
		this.BrowseRedditLabel = new global::Gtk.Label ();
		this.BrowseRedditLabel.Name = "BrowseRedditLabel";
		this.BrowseRedditLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("BROWSE REDDIT");
		this.BrowseRedditLabelContainer.Add (this.BrowseRedditLabel);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.BrowseRedditLabelContainer [this.BrowseRedditLabel]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		// Container child BrowseRedditLabelContainer.Gtk.Box+BoxChild
		this.BrowseRedditAligner = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.BrowseRedditAligner.Name = "BrowseRedditAligner";
		this.BrowseRedditLabelContainer.Add (this.BrowseRedditAligner);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.BrowseRedditLabelContainer [this.BrowseRedditAligner]));
		w9.Position = 1;
		this.BrowseRedditContainer.Add (this.BrowseRedditLabelContainer);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.BrowseRedditContainer [this.BrowseRedditLabelContainer]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child BrowseRedditContainer.Gtk.Box+BoxChild
		this.BrowseBtnsScrollWindow = new global::Gtk.ScrolledWindow ();
		this.BrowseBtnsScrollWindow.Name = "BrowseBtnsScrollWindow";
		// Container child BrowseBtnsScrollWindow.Gtk.Container+ContainerChild
		global::Gtk.Viewport w11 = new global::Gtk.Viewport ();
		w11.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child GtkViewport.Gtk.Container+ContainerChild
		this.BrowseBtnBox = new global::Gtk.HBox ();
		this.BrowseBtnBox.Name = "BrowseBtnBox";
		this.BrowseBtnBox.Spacing = 6;
		w11.Add (this.BrowseBtnBox);
		this.BrowseBtnsScrollWindow.Add (w11);
		this.BrowseRedditContainer.Add (this.BrowseBtnsScrollWindow);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.BrowseRedditContainer [this.BrowseBtnsScrollWindow]));
		w14.Position = 1;
		this.TopBarContainer.Add (this.BrowseRedditContainer);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.TopBarContainer [this.BrowseRedditContainer]));
		w15.Position = 2;
		// Container child TopBarContainer.Gtk.Box+BoxChild
		this.vseparator2 = new global::Gtk.VSeparator ();
		this.vseparator2.Name = "vseparator2";
		this.TopBarContainer.Add (this.vseparator2);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.TopBarContainer [this.vseparator2]));
		w16.Position = 3;
		w16.Expand = false;
		w16.Fill = false;
		// Container child TopBarContainer.Gtk.Box+BoxChild
		this.SearchContainer = new global::Gtk.VBox ();
		this.SearchContainer.Name = "SearchContainer";
		this.SearchContainer.Spacing = 10;
		// Container child SearchContainer.Gtk.Box+BoxChild
		this.SearchLabel = new global::Gtk.Label ();
		this.SearchLabel.Name = "SearchLabel";
		this.SearchLabel.Xalign = 0F;
		this.SearchLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("SEARCH REDDIT");
		this.SearchContainer.Add (this.SearchLabel);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.SearchContainer [this.SearchLabel]));
		w17.Position = 0;
		w17.Expand = false;
		w17.Fill = false;
		// Container child SearchContainer.Gtk.Box+BoxChild
		this.SearchOptsContainer = new global::Gtk.HBox ();
		this.SearchOptsContainer.Name = "SearchOptsContainer";
		this.SearchOptsContainer.Spacing = 6;
		// Container child SearchOptsContainer.Gtk.Box+BoxChild
		this.searchThisSub = new global::Gtk.CheckButton ();
		this.searchThisSub.CanFocus = true;
		this.searchThisSub.Name = "searchThisSub";
		this.searchThisSub.Label = global::Mono.Unix.Catalog.GetString ("In this Sub");
		this.searchThisSub.DrawIndicator = true;
		this.searchThisSub.UseUnderline = true;
		this.SearchOptsContainer.Add (this.searchThisSub);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.SearchOptsContainer [this.searchThisSub]));
		w18.Position = 0;
		// Container child SearchOptsContainer.Gtk.Box+BoxChild
		this.searchNsfw = new global::Gtk.CheckButton ();
		this.searchNsfw.CanFocus = true;
		this.searchNsfw.Name = "searchNsfw";
		this.searchNsfw.Label = global::Mono.Unix.Catalog.GetString ("Include NSFW");
		this.searchNsfw.DrawIndicator = true;
		this.searchNsfw.UseUnderline = true;
		this.SearchOptsContainer.Add (this.searchNsfw);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.SearchOptsContainer [this.searchNsfw]));
		w19.Position = 1;
		this.SearchContainer.Add (this.SearchOptsContainer);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.SearchContainer [this.SearchOptsContainer]));
		w20.Position = 1;
		w20.Expand = false;
		w20.Fill = false;
		// Container child SearchContainer.Gtk.Box+BoxChild
		this.SearchBarContainer = new global::Gtk.HBox ();
		this.SearchBarContainer.Name = "SearchBarContainer";
		this.SearchBarContainer.Spacing = 6;
		// Container child SearchBarContainer.Gtk.Box+BoxChild
		this.SearchEntry = new global::Gtk.Entry ();
		this.SearchEntry.CanFocus = true;
		this.SearchEntry.Name = "SearchEntry";
		this.SearchEntry.IsEditable = true;
		this.SearchEntry.InvisibleChar = '●';
		this.SearchBarContainer.Add (this.SearchEntry);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.SearchBarContainer [this.SearchEntry]));
		w21.Position = 0;
		// Container child SearchBarContainer.Gtk.Box+BoxChild
		this.SearchBtn = new global::Gtk.Button ();
		this.SearchBtn.CanFocus = true;
		this.SearchBtn.Name = "SearchBtn";
		this.SearchBtn.UseUnderline = true;
		this.SearchBtn.Label = global::Mono.Unix.Catalog.GetString ("Search");
		this.SearchBarContainer.Add (this.SearchBtn);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.SearchBarContainer [this.SearchBtn]));
		w22.Position = 1;
		w22.Expand = false;
		w22.Fill = false;
		this.SearchContainer.Add (this.SearchBarContainer);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.SearchContainer [this.SearchBarContainer]));
		w23.Position = 2;
		w23.Expand = false;
		w23.Fill = false;
		this.TopBarContainer.Add (this.SearchContainer);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.TopBarContainer [this.SearchContainer]));
		w24.PackType = ((global::Gtk.PackType)(1));
		w24.Position = 4;
		w24.Expand = false;
		w24.Fill = false;
		this.PrimaryContainer.Add (this.TopBarContainer);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.PrimaryContainer [this.TopBarContainer]));
		w25.Position = 0;
		w25.Expand = false;
		w25.Fill = false;
		// Container child PrimaryContainer.Gtk.Box+BoxChild
		this.ContentContainer = new global::Gtk.VBox ();
		this.ContentContainer.Name = "ContentContainer";
		this.ContentContainer.Spacing = 6;
		// Container child ContentContainer.Gtk.Box+BoxChild
		this.ContentPane = new global::Gtk.HPaned ();
		this.ContentPane.CanFocus = true;
		this.ContentPane.Name = "ContentPane";
		this.ContentPane.Position = 638;
		// Container child ContentPane.Gtk.Paned+PanedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		global::Gtk.Viewport w26 = new global::Gtk.Viewport ();
		w26.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child GtkViewport1.Gtk.Container+ContainerChild
		this.ListingBox = new global::Gtk.VBox ();
		this.ListingBox.Name = "ListingBox";
		this.ListingBox.Spacing = 6;
		w26.Add (this.ListingBox);
		this.GtkScrolledWindow.Add (w26);
		this.ContentPane.Add (this.GtkScrolledWindow);
		global::Gtk.Paned.PanedChild w29 = ((global::Gtk.Paned.PanedChild)(this.ContentPane [this.GtkScrolledWindow]));
		w29.Resize = false;
		this.ContentContainer.Add (this.ContentPane);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.ContentContainer [this.ContentPane]));
		w30.Position = 0;
		// Container child ContentContainer.Gtk.Box+BoxChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		this.ContentContainer.Add (this.fixed1);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.ContentContainer [this.fixed1]));
		w31.Position = 1;
		w31.Expand = false;
		w31.Fill = false;
		this.PrimaryContainer.Add (this.ContentContainer);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.PrimaryContainer [this.ContentContainer]));
		w32.Position = 1;
		this.MainContainer.Add (this.PrimaryContainer);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.MainContainer [this.PrimaryContainer]));
		w33.Position = 1;
		// Container child MainContainer.Gtk.Box+BoxChild
		this.BottomBarContainer = new global::Gtk.HBox ();
		this.BottomBarContainer.Name = "BottomBarContainer";
		this.BottomBarContainer.Spacing = 6;
		this.BottomBarContainer.BorderWidth = ((uint)(10));
		// Container child BottomBarContainer.Gtk.Box+BoxChild
		this.NotifyContainer = new global::Gtk.VBox ();
		this.NotifyContainer.Name = "NotifyContainer";
		this.NotifyContainer.Spacing = 6;
		// Container child NotifyContainer.Gtk.Box+BoxChild
		this.NotifyLabelBox = new global::Gtk.HBox ();
		this.NotifyLabelBox.Name = "NotifyLabelBox";
		this.NotifyLabelBox.Spacing = 6;
		// Container child NotifyLabelBox.Gtk.Box+BoxChild
		this.NotifyLabel = new global::Gtk.Label ();
		this.NotifyLabel.Name = "NotifyLabel";
		this.NotifyLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("NOTIFICATIONS");
		this.NotifyLabelBox.Add (this.NotifyLabel);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.NotifyLabelBox [this.NotifyLabel]));
		w34.Position = 0;
		w34.Expand = false;
		w34.Fill = false;
		this.NotifyContainer.Add (this.NotifyLabelBox);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.NotifyContainer [this.NotifyLabelBox]));
		w35.Position = 0;
		w35.Expand = false;
		w35.Fill = false;
		// Container child NotifyContainer.Gtk.Box+BoxChild
		this.NotifyBtnContainer = new global::Gtk.HBox ();
		this.NotifyBtnContainer.Name = "NotifyBtnContainer";
		this.NotifyBtnContainer.Spacing = 6;
		// Container child NotifyBtnContainer.Gtk.Box+BoxChild
		this.messagesBtn = new global::Gtk.Button ();
		this.messagesBtn.CanFocus = true;
		this.messagesBtn.Name = "messagesBtn";
		this.messagesBtn.UseUnderline = true;
		// Container child messagesBtn.Gtk.Container+ContainerChild
		global::Gtk.Alignment w36 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w37 = new global::Gtk.HBox ();
		w37.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w38 = new global::Gtk.Image ();
		w38.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_mail-unread", global::Gtk.IconSize.Menu);
		w37.Add (w38);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w40 = new global::Gtk.Label ();
		w40.LabelProp = global::Mono.Unix.Catalog.GetString ("1 New Message");
		w40.UseUnderline = true;
		w37.Add (w40);
		w36.Add (w37);
		this.messagesBtn.Add (w36);
		this.NotifyBtnContainer.Add (this.messagesBtn);
		global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.NotifyBtnContainer [this.messagesBtn]));
		w44.Position = 0;
		w44.Expand = false;
		w44.Fill = false;
		// Container child NotifyBtnContainer.Gtk.Box+BoxChild
		this.comRepliesBtn = new global::Gtk.Button ();
		this.comRepliesBtn.CanFocus = true;
		this.comRepliesBtn.Name = "comRepliesBtn";
		this.comRepliesBtn.UseUnderline = true;
		// Container child comRepliesBtn.Gtk.Container+ContainerChild
		global::Gtk.Alignment w45 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w46 = new global::Gtk.HBox ();
		w46.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w47 = new global::Gtk.Image ();
		w47.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-dialog-info", global::Gtk.IconSize.Menu);
		w46.Add (w47);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w49 = new global::Gtk.Label ();
		w49.LabelProp = global::Mono.Unix.Catalog.GetString ("2 New Comment Replies");
		w49.UseUnderline = true;
		w46.Add (w49);
		w45.Add (w46);
		this.comRepliesBtn.Add (w45);
		this.NotifyBtnContainer.Add (this.comRepliesBtn);
		global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.NotifyBtnContainer [this.comRepliesBtn]));
		w53.Position = 1;
		w53.Expand = false;
		w53.Fill = false;
		// Container child NotifyBtnContainer.Gtk.Box+BoxChild
		this.PostRepliesBtn = new global::Gtk.Button ();
		this.PostRepliesBtn.CanFocus = true;
		this.PostRepliesBtn.Name = "PostRepliesBtn";
		this.PostRepliesBtn.UseUnderline = true;
		// Container child PostRepliesBtn.Gtk.Container+ContainerChild
		global::Gtk.Alignment w54 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w55 = new global::Gtk.HBox ();
		w55.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w56 = new global::Gtk.Image ();
		w56.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-dialog-warning", global::Gtk.IconSize.Menu);
		w55.Add (w56);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w58 = new global::Gtk.Label ();
		w58.LabelProp = global::Mono.Unix.Catalog.GetString ("Post Replies");
		w58.UseUnderline = true;
		w55.Add (w58);
		w54.Add (w55);
		this.PostRepliesBtn.Add (w54);
		this.NotifyBtnContainer.Add (this.PostRepliesBtn);
		global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.NotifyBtnContainer [this.PostRepliesBtn]));
		w62.Position = 2;
		w62.Expand = false;
		w62.Fill = false;
		this.NotifyContainer.Add (this.NotifyBtnContainer);
		global::Gtk.Box.BoxChild w63 = ((global::Gtk.Box.BoxChild)(this.NotifyContainer [this.NotifyBtnContainer]));
		w63.Position = 1;
		w63.Expand = false;
		w63.Fill = false;
		this.BottomBarContainer.Add (this.NotifyContainer);
		global::Gtk.Box.BoxChild w64 = ((global::Gtk.Box.BoxChild)(this.BottomBarContainer [this.NotifyContainer]));
		w64.Position = 0;
		w64.Expand = false;
		w64.Fill = false;
		// Container child BottomBarContainer.Gtk.Box+BoxChild
		this.vseparator3 = new global::Gtk.VSeparator ();
		this.vseparator3.Name = "vseparator3";
		this.BottomBarContainer.Add (this.vseparator3);
		global::Gtk.Box.BoxChild w65 = ((global::Gtk.Box.BoxChild)(this.BottomBarContainer [this.vseparator3]));
		w65.Position = 1;
		w65.Expand = false;
		w65.Fill = false;
		this.MainContainer.Add (this.BottomBarContainer);
		global::Gtk.Box.BoxChild w66 = ((global::Gtk.Box.BoxChild)(this.MainContainer [this.BottomBarContainer]));
		w66.PackType = ((global::Gtk.PackType)(1));
		w66.Position = 2;
		w66.Expand = false;
		w66.Fill = false;
		this.Add (this.MainContainer);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.QuitAction.Activated += new global::System.EventHandler (this.OnFileQuit);
		this.LogOutAction.Activated += new global::System.EventHandler (this.OnLogOut);
	}
}
