
// This file has been generated by the GUI designer. Do not modify.
namespace RedditDesktop
{
	public partial class LoginWindow
	{
		private global::Gtk.VBox loginContainer;
		private global::Gtk.HBox LogoContainer;
		private global::Gtk.VBox loginForm;
		private global::Gtk.VBox loginField1;
		private global::Gtk.Alignment alignment4;
		private global::Gtk.Label userLabel;
		private global::Gtk.Alignment alignment5;
		private global::Gtk.Entry userEntry;
		private global::Gtk.Alignment alignment6;
		private global::Gtk.Label passLabel;
		private global::Gtk.Alignment loginField2;
		private global::Gtk.Entry passEntry;
		private global::Gtk.HBox loginField3;
		private global::Gtk.Button loginBtn;
		private global::Gtk.CheckButton rememberBtn;
		private global::Gtk.VBox StatusContainer;
		private global::Gtk.HSeparator hseparator3;
		private global::Gtk.Label loginStatusLabel;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget RedditDesktop.LoginWindow
			this.Name = "RedditDesktop.LoginWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Reddit Desktop Login");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Resizable = false;
			// Container child RedditDesktop.LoginWindow.Gtk.Container+ContainerChild
			this.loginContainer = new global::Gtk.VBox ();
			this.loginContainer.Name = "loginContainer";
			this.loginContainer.Spacing = -4;
			// Container child loginContainer.Gtk.Box+BoxChild
			this.LogoContainer = new global::Gtk.HBox ();
			this.LogoContainer.Name = "LogoContainer";
			this.LogoContainer.Spacing = 6;
			this.loginContainer.Add (this.LogoContainer);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.loginContainer [this.LogoContainer]));
			w1.Position = 0;
			// Container child loginContainer.Gtk.Box+BoxChild
			this.loginForm = new global::Gtk.VBox ();
			this.loginForm.Name = "loginForm";
			this.loginForm.Spacing = 6;
			// Container child loginForm.Gtk.Box+BoxChild
			this.loginField1 = new global::Gtk.VBox ();
			this.loginField1.Name = "loginField1";
			this.loginField1.Spacing = 6;
			// Container child loginField1.Gtk.Box+BoxChild
			this.alignment4 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment4.Name = "alignment4";
			this.alignment4.RightPadding = ((uint)(181));
			// Container child alignment4.Gtk.Container+ContainerChild
			this.userLabel = new global::Gtk.Label ();
			this.userLabel.Name = "userLabel";
			this.userLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Reddit Username");
			this.alignment4.Add (this.userLabel);
			this.loginField1.Add (this.alignment4);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.loginField1 [this.alignment4]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child loginField1.Gtk.Box+BoxChild
			this.alignment5 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment5.Name = "alignment5";
			this.alignment5.LeftPadding = ((uint)(60));
			this.alignment5.RightPadding = ((uint)(60));
			// Container child alignment5.Gtk.Container+ContainerChild
			this.userEntry = new global::Gtk.Entry ();
			this.userEntry.CanFocus = true;
			this.userEntry.Name = "userEntry";
			this.userEntry.IsEditable = true;
			this.userEntry.InvisibleChar = '●';
			this.alignment5.Add (this.userEntry);
			this.loginField1.Add (this.alignment5);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.loginField1 [this.alignment5]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child loginField1.Gtk.Box+BoxChild
			this.alignment6 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment6.Name = "alignment6";
			this.alignment6.RightPadding = ((uint)(183));
			// Container child alignment6.Gtk.Container+ContainerChild
			this.passLabel = new global::Gtk.Label ();
			this.passLabel.Name = "passLabel";
			this.passLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Reddit Password");
			this.alignment6.Add (this.passLabel);
			this.loginField1.Add (this.alignment6);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.loginField1 [this.alignment6]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			this.loginForm.Add (this.loginField1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.loginForm [this.loginField1]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child loginForm.Gtk.Box+BoxChild
			this.loginField2 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.loginField2.Name = "loginField2";
			this.loginField2.LeftPadding = ((uint)(60));
			this.loginField2.RightPadding = ((uint)(60));
			// Container child loginField2.Gtk.Container+ContainerChild
			this.passEntry = new global::Gtk.Entry ();
			this.passEntry.CanFocus = true;
			this.passEntry.Name = "passEntry";
			this.passEntry.IsEditable = true;
			this.passEntry.Visibility = false;
			this.passEntry.InvisibleChar = '●';
			this.loginField2.Add (this.passEntry);
			this.loginForm.Add (this.loginField2);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.loginForm [this.loginField2]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			// Container child loginForm.Gtk.Box+BoxChild
			this.loginField3 = new global::Gtk.HBox ();
			this.loginField3.Name = "loginField3";
			this.loginField3.Spacing = -48;
			// Container child loginField3.Gtk.Box+BoxChild
			this.loginBtn = new global::Gtk.Button ();
			this.loginBtn.Sensitive = false;
			this.loginBtn.CanFocus = true;
			this.loginBtn.Name = "loginBtn";
			this.loginBtn.UseUnderline = true;
			// Container child loginBtn.Gtk.Container+ContainerChild
			global::Gtk.Alignment w11 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w12 = new global::Gtk.HBox ();
			w12.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w13 = new global::Gtk.Image ();
			w13.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-home", global::Gtk.IconSize.Button);
			w12.Add (w13);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w15 = new global::Gtk.Label ();
			w15.LabelProp = global::Mono.Unix.Catalog.GetString ("Login to Reddit Desktop");
			w15.UseUnderline = true;
			w12.Add (w15);
			w11.Add (w12);
			this.loginBtn.Add (w11);
			this.loginField3.Add (this.loginBtn);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.loginField3 [this.loginBtn]));
			w19.Position = 0;
			w19.Expand = false;
			w19.Fill = false;
			w19.Padding = ((uint)(58));
			// Container child loginField3.Gtk.Box+BoxChild
			this.rememberBtn = new global::Gtk.CheckButton ();
			this.rememberBtn.CanFocus = true;
			this.rememberBtn.Name = "rememberBtn";
			this.rememberBtn.Label = global::Mono.Unix.Catalog.GetString ("Remember Me");
			this.rememberBtn.DrawIndicator = true;
			this.rememberBtn.UseUnderline = true;
			this.loginField3.Add (this.rememberBtn);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.loginField3 [this.rememberBtn]));
			w20.Position = 1;
			this.loginForm.Add (this.loginField3);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.loginForm [this.loginField3]));
			w21.Position = 2;
			w21.Expand = false;
			w21.Fill = false;
			w21.Padding = ((uint)(10));
			// Container child loginForm.Gtk.Box+BoxChild
			this.StatusContainer = new global::Gtk.VBox ();
			this.StatusContainer.Name = "StatusContainer";
			this.StatusContainer.Spacing = -8;
			// Container child StatusContainer.Gtk.Box+BoxChild
			this.hseparator3 = new global::Gtk.HSeparator ();
			this.hseparator3.Name = "hseparator3";
			this.StatusContainer.Add (this.hseparator3);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.StatusContainer [this.hseparator3]));
			w22.Position = 0;
			w22.Expand = false;
			w22.Fill = false;
			// Container child StatusContainer.Gtk.Box+BoxChild
			this.loginStatusLabel = new global::Gtk.Label ();
			this.loginStatusLabel.Name = "loginStatusLabel";
			this.loginStatusLabel.Ypad = 15;
			this.loginStatusLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Please log in using your reddit account.");
			this.StatusContainer.Add (this.loginStatusLabel);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.StatusContainer [this.loginStatusLabel]));
			w23.Position = 1;
			w23.Expand = false;
			w23.Fill = false;
			this.loginForm.Add (this.StatusContainer);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.loginForm [this.StatusContainer]));
			w24.Position = 3;
			w24.Expand = false;
			w24.Fill = false;
			this.loginContainer.Add (this.loginForm);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.loginContainer [this.loginForm]));
			w25.Position = 1;
			w25.Expand = false;
			w25.Fill = false;
			this.Add (this.loginContainer);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 406;
			this.DefaultHeight = 536;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDelete);
			this.KeyReleaseEvent += new global::Gtk.KeyReleaseEventHandler (this.OnKeyRelease);
			this.loginBtn.Clicked += new global::System.EventHandler (this.OnLoginClick);
		}
	}
}
